default:
  before_script:
    - sudo apt-get -y update --fix-missing
    - >
      sudo apt-get -y install -y -qq  git gcc make
      autoconf automake autopoint pkg-config libtool libtool-bin gettext
      libssl-dev libdevmapper-dev libpopt-dev uuid-dev libsepol1-dev
      libjson-c-dev libssh-dev libblkid-dev tar libargon2-0-dev
      libpwquality-dev sharutils dmsetup jq xxd expect keyutils
      netcat passwd openssh-client sshpass
    - sudo apt-get -y build-dep cryptsetup
    - sudo -E git clean -xdf
    - ./autogen.sh
    - ./configure --enable-libargon2

stages:
  - test

# Merge request: Build and run only non-root tests
test-mergerq-job:
  stage: test
  interruptible: true
  rules:
    - if: $CI_PROJECT_PATH != "cryptsetup/cryptsetup"
      when: never
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  script:
    - make -j
    - make -j -C tests check-programs
    - make check

# For main branch commit, run all tests as root
test-main-commit-job:
  stage: test
  interruptible: true
  variables:
    RUN_SSH_PLUGIN_TEST: "1"
  rules:
    - if: $CI_PROJECT_PATH != "cryptsetup/cryptsetup"
      when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - make -j
    - make -j -C tests check-programs
    - sudo -E make check
    - sudo -E make clean
